import { Locale, RoutineCategory } from '@prisma/client';

export const DEMO_USER = {
  email: 'alex@postureflow.app',
  firstName: 'Alex',
  lastName: 'Carter',
  locale: Locale.EN,
};

export const PAIN_REGIONS = [
  {
    id: 'neck',
    nameEn: 'Neck',
    nameEs: 'Cuello',
    shape: 'circle',
    cx: 100,
    cy: 60,
    radius: 25,
    sortOrder: 1,
  },
  {
    id: 'shoulders',
    nameEn: 'Shoulders',
    nameEs: 'Hombros',
    shape: 'ellipse',
    cx: 100,
    cy: 110,
    radiusX: 70,
    radiusY: 20,
    sortOrder: 2,
  },
  {
    id: 'chest',
    nameEn: 'Chest',
    nameEs: 'Pecho',
    shape: 'ellipse',
    cx: 100,
    cy: 145,
    radiusX: 42,
    radiusY: 24,
    sortOrder: 3,
  },
  {
    id: 'arms',
    nameEn: 'Arms',
    nameEs: 'Brazos',
    shape: 'ellipse',
    cx: 100,
    cy: 180,
    radiusX: 78,
    radiusY: 28,
    sortOrder: 4,
  },
  {
    id: 'forearms',
    nameEn: 'Forearms',
    nameEs: 'Antebrazos',
    shape: 'ellipse',
    cx: 100,
    cy: 220,
    radiusX: 86,
    radiusY: 22,
    sortOrder: 5,
  },
  {
    id: 'hands',
    nameEn: 'Hands',
    nameEs: 'Manos',
    shape: 'ellipse',
    cx: 100,
    cy: 255,
    radiusX: 90,
    radiusY: 18,
    sortOrder: 6,
  },
  {
    id: 'core',
    nameEn: 'Core',
    nameEs: 'Core',
    shape: 'ellipse',
    cx: 100,
    cy: 220,
    radiusX: 34,
    radiusY: 38,
    sortOrder: 7,
  },
  {
    id: 'upper_back',
    nameEn: 'Upper Back',
    nameEs: 'Espalda Alta',
    shape: 'ellipse',
    cx: 100,
    cy: 160,
    radiusX: 45,
    radiusY: 35,
    sortOrder: 8,
  },
  {
    id: 'lower_back',
    nameEn: 'Lower Back',
    nameEs: 'Lumbares',
    shape: 'ellipse',
    cx: 100,
    cy: 230,
    radiusX: 40,
    radiusY: 35,
    sortOrder: 9,
  },
  {
    id: 'hips',
    nameEn: 'Hips',
    nameEs: 'Caderas',
    shape: 'ellipse',
    cx: 100,
    cy: 290,
    radiusX: 50,
    radiusY: 25,
    sortOrder: 10,
  },
  {
    id: 'legs',
    nameEn: 'Legs',
    nameEs: 'Piernas',
    shape: 'ellipse',
    cx: 100,
    cy: 360,
    radiusX: 52,
    radiusY: 34,
    sortOrder: 11,
  },
  {
    id: 'knees',
    nameEn: 'Knees',
    nameEs: 'Rodillas',
    shape: 'ellipse',
    cx: 100,
    cy: 420,
    radiusX: 40,
    radiusY: 20,
    sortOrder: 12,
  },
  {
    id: 'calves',
    nameEn: 'Calves',
    nameEs: 'Pantorrillas',
    shape: 'ellipse',
    cx: 100,
    cy: 475,
    radiusX: 38,
    radiusY: 28,
    sortOrder: 13,
  },
  {
    id: 'feet',
    nameEn: 'Feet',
    nameEs: 'Pies',
    shape: 'ellipse',
    cx: 100,
    cy: 540,
    radiusX: 42,
    radiusY: 18,
    sortOrder: 14,
  },
];

export const SETUP_OPTIONS = [
  {
    id: 'deep_focus',
    titleEn: 'Deep Focus (The Zone)',
    titleEs: 'Deep Focus (La Zona)',
    descriptionEn: 'Physical tension but high mental energy. Fast-paced flow.',
    descriptionEs: 'Tension fisica pero energia mental alta. Flujo de ritmo rapido.',
    icon: 'Cpu',
    sortOrder: 1,
  },
  {
    id: 'digital_fatigue',
    titleEn: 'Digital Fatigue',
    titleEs: 'Fatiga Digital',
    descriptionEn: 'Eye strain and mental fog. Focus on slow movements and ocular relief.',
    descriptionEs: 'Fatiga visual y niebla mental. Prioriza movimientos lentos y alivio ocular.',
    icon: 'Eye',
    sortOrder: 2,
  },
  {
    id: 'burnout',
    titleEn: 'End of Shift / Burnout',
    titleEs: 'Fin de Turno / Burnout',
    descriptionEn: 'Full body exhaustion. Pure restorative and grounding session.',
    descriptionEs: 'Agotamiento corporal completo. Sesion puramente restaurativa y de aterrizaje.',
    icon: 'BatteryLow',
    sortOrder: 3,
  },
];

export const ROUTINES = [
  {
    slug: 'deep-cervical-decompression',
    titleEn: 'Deep Cervical Decompression',
    titleEs: 'Descompresion Cervical Profunda',
    subtitleEn: 'Daily recommendation',
    subtitleEs: 'Sugerencia diaria',
    descriptionEn: 'Chair-based release for neck and shoulder tension.',
    descriptionEs: 'Liberacion en silla para cuello y hombros.',
    imageUrl:
      'https://images.unsplash.com/photo-1622131243631-1cf9ff4a8b9e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxvZmZpY2UlMjB3ZWxsbmVzcyUyMGluc3RydWN0b3J8ZW58MXx8fHwxNzc2ODExMTMzfDA&ixlib=rb-4.1.0&q=80&w=1080',
    durationMinutes: 4,
    sizeMb: 12,
    category: RoutineCategory.RELIEF,
    featured: true,
    targetPainRegionIds: ['neck', 'shoulders', 'upper_back'],
    targetSetupOptionIds: ['deep_focus', 'digital_fatigue'],
    sortOrder: 1,
  },
  {
    slug: 'lumbar-reset',
    titleEn: 'Lumbar Reset',
    titleEs: 'Reseteo Lumbar',
    subtitleEn: 'Desk decompression',
    subtitleEs: 'Descompresion de escritorio',
    descriptionEn: 'A seated sequence for pelvic tilt and lower back relief.',
    descriptionEs: 'Secuencia sentada para aliviar pelvis y espalda baja.',
    imageUrl:
      'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtZWRpdGF0aW9ufGVufDB8fHx8MTY5OTMwOTM1M3ww&ixlib=rb-4.0.3&q=80&w=400',
    durationMinutes: 5,
    sizeMb: 18,
    category: RoutineCategory.RECOVERY,
    featured: false,
    targetPainRegionIds: ['lower_back', 'hips', 'core', 'legs'],
    targetSetupOptionIds: ['burnout'],
    sortOrder: 2,
  },
  {
    slug: 'chest-opening',
    titleEn: 'Chest Opening Reset',
    titleEs: 'Apertura de Pecho',
    subtitleEn: 'Upper-back mobility',
    subtitleEs: 'Movilidad toracica',
    descriptionEn: 'Undo rounded shoulders with thoracic opening.',
    descriptionEs: 'Revierte hombros cerrados con apertura toracica.',
    imageUrl:
      'https://images.unsplash.com/photo-1506126613408-eca07ce68773?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtZWRpdGF0aW9ufGVufDB8fHx8MTY5OTMwOTM1M3ww&ixlib=rb-4.0.3&q=80&w=400',
    durationMinutes: 4,
    sizeMb: 15,
    category: RoutineCategory.MOBILITY,
    featured: false,
    targetPainRegionIds: ['chest', 'shoulders', 'upper_back', 'arms'],
    targetSetupOptionIds: ['digital_fatigue', 'deep_focus'],
    sortOrder: 3,
  },
  {
    slug: 'flight-mode-calm',
    titleEn: 'Flight Mode Calm',
    titleEs: 'Modo Avion Calmante',
    subtitleEn: 'Breath-led recovery',
    subtitleEs: 'Recuperacion con respiracion',
    descriptionEn: 'Breathwork for stress and mental reset while seated.',
    descriptionEs: 'Respiracion guiada para bajar estres y resetear la mente.',
    imageUrl:
      'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtZWRpdGF0aW9ufGVufDB8fHx8MTY5OTMwOTM1M3ww&ixlib=rb-4.0.3&q=80&w=400',
    durationMinutes: 3,
    sizeMb: 10,
    category: RoutineCategory.BREATHWORK,
    featured: false,
    targetPainRegionIds: ['neck', 'upper_back', 'chest', 'core'],
    targetSetupOptionIds: ['burnout', 'digital_fatigue'],
    sortOrder: 4,
  },
];
