import type {
  BodyVideoCatalogItem,
  TargetBodyPart,
} from './body-video-recommendations.model';

export const BODY_PART_ALIASES: Record<string, TargetBodyPart> = {
  arm: 'brazos',
  arms: 'brazos',
  antebrazos: 'antebrazos',
  back_lower: 'espalda_baja',
  brazos: 'brazos',
  calves: 'pantorrillas',
  caderas: 'caderas',
  chest: 'pecho',
  core: 'core',
  cuello: 'cuello',
  espalda_alta: 'espalda_alta',
  espalda_baja: 'espalda_baja',
  feet: 'pies',
  forearms: 'antebrazos',
  hands: 'manos',
  hips: 'caderas',
  hombros: 'hombros',
  knees: 'rodillas',
  legs: 'piernas',
  lower_back: 'espalda_baja',
  lumbar: 'espalda_baja',
  lumbares: 'espalda_baja',
  manos: 'manos',
  neck: 'cuello',
  pantorrillas: 'pantorrillas',
  pecho: 'pecho',
  piernas: 'piernas',
  pies: 'pies',
  rodillas: 'rodillas',
  shoulder: 'hombros',
  shoulders: 'hombros',
  upper_back: 'espalda_alta',
};

export const SUPPORTED_BODY_PARTS = [
  ...new Set(Object.values(BODY_PART_ALIASES)),
];

// Timestamps are stored in seconds because YouTube player APIs expect seconds.
// startTime 0 with endTime null means the whole video can be played.
// Any non-zero startTime and finite endTime represents a useful segment inside
// a longer routine, so the React Native player can seek directly to that clip.
export const BODY_VIDEO_CATALOG: BodyVideoCatalogItem[] = [
  {
    id: 'neck-breath-posture-reset',
    youtubeId: 'UCTjyqX_vZ0',
    title: 'Reset cervical sentado con respiracion',
    targetBodyPart: 'cuello',
    startTime: 12,
    endTime: 42,
    sortOrder: 1,
  },
  {
    id: 'neck-complete-flow-segment',
    youtubeId: '-dzJZriroQA',
    title: 'Segmento cervical de Tai Chi en silla',
    targetBodyPart: 'cuello',
    startTime: 31,
    endTime: 72,
    sortOrder: 2,
  },
  {
    id: 'shoulder-upper-body-flow',
    youtubeId: 'PMXleOOpYjo',
    title: 'Flujo suave para hombros cerrados',
    targetBodyPart: 'hombros',
    startTime: 24,
    endTime: 58,
    sortOrder: 3,
  },
  {
    id: 'shoulder-breath-posture-reset',
    youtubeId: 'UCTjyqX_vZ0',
    title: 'Descarga de cuello y hombros',
    targetBodyPart: 'hombros',
    startTime: 12,
    endTime: 42,
    sortOrder: 4,
  },
  {
    id: 'upper-back-thoracic-open',
    youtubeId: 'PMXleOOpYjo',
    title: 'Apertura toracica para espalda alta',
    targetBodyPart: 'espalda_alta',
    startTime: 58,
    endTime: 118,
    sortOrder: 5,
  },
  {
    id: 'lower-back-chair-foundation',
    youtubeId: '7nUePhUPZJk',
    title: 'Fundacion sentada para espalda baja',
    targetBodyPart: 'espalda_baja',
    startTime: 18,
    endTime: 52,
    sortOrder: 6,
  },
  {
    id: 'hips-lower-body-foundation',
    youtubeId: '7nUePhUPZJk',
    title: 'Movilidad suave para caderas',
    targetBodyPart: 'caderas',
    startTime: 52,
    endTime: 92,
    sortOrder: 7,
  },
  {
    id: 'core-posture-complete-flow',
    youtubeId: '-dzJZriroQA',
    title: 'Centro estable en flujo postural completo',
    targetBodyPart: 'core',
    startTime: 72,
    endTime: 132,
    sortOrder: 8,
  },
  {
    id: 'chest-thoracic-open',
    youtubeId: 'PMXleOOpYjo',
    title: 'Apertura de pecho y respiracion',
    targetBodyPart: 'pecho',
    startTime: 58,
    endTime: 118,
    sortOrder: 9,
  },
  {
    id: 'arms-upper-body-flow',
    youtubeId: 'PMXleOOpYjo',
    title: 'Flujo de brazos para escritorio',
    targetBodyPart: 'brazos',
    startTime: 118,
    endTime: 168,
    sortOrder: 10,
  },
  {
    id: 'forearms-hands-release',
    youtubeId: 'PMXleOOpYjo',
    title: 'Liberacion de antebrazos y manos',
    targetBodyPart: 'antebrazos',
    startTime: 168,
    endTime: 210,
    sortOrder: 11,
  },
  {
    id: 'hands-release',
    youtubeId: 'PMXleOOpYjo',
    title: 'Micro pausa para manos',
    targetBodyPart: 'manos',
    startTime: 180,
    endTime: 210,
    sortOrder: 12,
  },
  {
    id: 'legs-lower-body-foundation',
    youtubeId: '7nUePhUPZJk',
    title: 'Activacion de piernas en silla',
    targetBodyPart: 'piernas',
    startTime: 92,
    endTime: 132,
    sortOrder: 13,
  },
  {
    id: 'knees-lower-body-foundation',
    youtubeId: '7nUePhUPZJk',
    title: 'Movilidad amable para rodillas',
    targetBodyPart: 'rodillas',
    startTime: 132,
    endTime: 168,
    sortOrder: 14,
  },
  {
    id: 'calves-feet-grounding',
    youtubeId: '7nUePhUPZJk',
    title: 'Pantorrillas y pies para volver al suelo',
    targetBodyPart: 'pantorrillas',
    startTime: 168,
    endTime: 205,
    sortOrder: 15,
  },
  {
    id: 'feet-grounding',
    youtubeId: '7nUePhUPZJk',
    title: 'Anclaje sentado para pies',
    targetBodyPart: 'pies',
    startTime: 182,
    endTime: 205,
    sortOrder: 16,
  },
  {
    id: 'lower-back-complete-video',
    youtubeId: '-dzJZriroQA',
    title: 'Tai Chi sentado completo para descarga lumbar',
    targetBodyPart: 'espalda_baja',
    startTime: 0,
    endTime: null,
    sortOrder: 17,
  },
];
